config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", as: "rate"
  devise_for :users, controllers: {omniauth_callbacks: "callbacks",
    registrations: "users"}

  scope "(:locale)", locale: /en|vi|ja/ do
    root "static_pages#home"

    resources :users
    resources :blogs
    resources :news
    resources :likes
    resources :comments
    resources :contacts
    resources :categories
    resources :like_blogs
    resources :projects do
      resources :participates
    end
    namespace :admin do
      root "admin#index"
      resources :homes
      resources :users
      resources :projects do
        resources :participates
      end
    end
    resources :messages
  end

  mount ActionCable.server => "/cable"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    if user && (user.has_role? User::ROLES[:admin])
      can :manage, :all
      can [:update, :destroy, :new], [Post, Project]
    else
      can :manage, [Post, Project]
      can :read, :all
    end
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :post
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :projects, dependent: :destroy

  enum target_type: {blog: 0, news: 1, project: 2}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :target, polymorphic: true

  scope :order_by_newest, ->{order created_at: :desc}
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true,
   length: {maximum: Settings.contact.name_length}
  validates :email, presence: true,
   length: {maximum: Settings.contact.email_length}
  validates :title, presence: true,
   length: {maximum: Settings.contact.title_length}
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :project
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :images, as: :target

  accepts_nested_attributes_for :images, allow_destroy: true

  enum language: {en: 0, vi: 1, ja: 2}
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :target, polymorphic: true

  mount_uploader :image, ImageUploader,
    reject_if: proc{ |param| param[:image].blank? && param[:image_cache].blank? &&
    param[:id].blank? }, allow_destroy: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :project

  after_create_commit {MessageBroadcastJob.perform_now self}
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user_create, class_name: User.name
  belongs_to :user
  belongs_to :notificationable, polymorphic: true

  scope :order_by_newest, ->{order created_at: :desc}
  scope :uncheck, ->{where(checked: false).count}
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :user
  belongs_to :project

  scope :accepted, ->{where is_accept: true}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :attachments, dependent: :destroy
  has_many :likes, as: :target
  has_many :comments, as: :target
  has_many :notifications, as: :notificationable

  mount_uploader :image, ImageUploader

  delegate :name, to: :category, prefix: :category, allow_nil: true
  delegate :name, to: :user, prefix: :user, allow_nil: true

  validates :title, presence: true
  validates :content, presence: true

  enum target_type: {blog: 0, news: 1}

  scope :order_by_newest, ->{order created_at: :desc}
  scope :post_by_category_and_type, -> category_id, target_type do
    where category: category_id, target_type: target_type
  end
  scope :except_id, ->id do
    where("id != ?", id).limit Settings.related_item
  end

  ratyrate_rateable :rating
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  has_many :feedbacks, dependent: :destroy
  has_many :participates, dependent: :destroy
  has_many :users, through: :participates
  has_many :messages, dependent: :destroy
  has_many :likes, as: :target
  has_many :images, as: :target
  has_many :targettechniques, as: :target
  has_many :comments, as: :target

  scope :order_by_newest, ->{order created_at: :desc}

  accepts_nested_attributes_for :images, allow_destroy: true


  validates :name, presence: true,
   length: {maximum: Settings.project.name_length}
  validates :url, presence: true,
   length: {maximum: Settings.project.url_length}
  validates :description, presence: true,
   length: {maximum: Settings.project.description_length}
  validates :realease_note, presence: true,
   length: {maximum: Settings.project.realease_note_length}
  validates :git_repository, presence: true,
   length: {maximum: Settings.project.git_repository_length}
  validates :server_information, presence: true,
   length: {maximum: Settings.project.server_information_length}
  validates :platform, presence: true,
   length: {maximum: Settings.project.platform_length}
  validates :core_features, presence: true,
   length: {maximum: Settings.project.core_features_length}
  validates :pm_url, presence: true,
   length: {maximum: Settings.project.pm_url_length}

  ratyrate_rateable :rating

  PRIVATE_ATTRIBUTES = {server_information: "server_information",
    git_repository: "git_repository", pm_url: "pm_url"}

  BRANCH = [[Settings.branch.hanoi, 0],[Settings.branch.danang, 1]]
  private

  def check_max_files
    if images.blank? || images.size > Settings.project.max_image_files
      errors.add(:dagger, I18n.t("projects.check_max_files"))
    end
  end

  def self.show_for_rating
    Project.all.sort_by {|u| [u.average(:rating) ? u.average(:rating).avg : 0, u.average(:rating)]}.reverse
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource, polymorphic: true, optional: true

  validates :resource_type, inclusion: {in: Rolify.resource_types}, allow_nil: true

  scopify
end

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :user
end

app/models/technique.rb
class Technique < ApplicationRecord
  has_many :target_techniques, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, omniauth_providers: [:facebook, :twitter]

  has_many :socials, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :participates, dependent: :destroy
  has_many :projects, through: :participates
  has_many :techniques, through: :target_techniques
  has_many :messages, dependent: :destroy
  has_many :certificate_users, dependent: :destroy
  has_many :certifications, through: :certificate_users
  has_many :likes, as: :target
  has_many :target_techniques, as: :target
  has_many :notifications, dependent: :destroy

  mount_uploader :avatar, ImageUploader
  mount_uploader :cover_photo, ImageUploader

  ROLES = {admin: "Admin", user: "User"}

  validates :name, presence: true, length: {maximum: Settings.user.name}

  scope :order_by_newest, ->{order created_at: :desc}
  scope :member_not_in_project, lambda { |ids| where(["id NOT IN (?)", ids]) if ids.any? }

  ratyrate_rateable :rating

  ratyrate_rater

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name unless auth.info.name.nil?
      user.email = auth.info.email unless auth.info.email.nil?
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::AdminController
  before_action :authenticate_user!
    def index
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @contact = Contact.new
    @key = Settings.link_map + ENV["GOOGLE_API_KEY"]
    @projects = Project.show_for_rating.take Settings.limit_project
    @home = Home.en.last
    if params[:locale] == Settings.language.vi
      @home = Home.vi.last
    elsif params[:locale] == Settings.language.ja
      @home = Home.ja.last
    end
  end
end

app/views/static_pages/_list_project.html.erb
<% @projects.each do |project| %>
  <div class="col-md-4 col-sm-6">
    <div class="portfolio-content">
      <%= image_tag project.images.first.image.url, class: "img-responsive resize-project"%>
      <div class="portfolio-overlay">
        <%= link_to project_path(I18n.locale, project) do %>
          <i class="fa fa-camera-retro"></i>
        <% end %>
        <h5><%= project.name %></h5>
        <p><%= project.description.truncate(Settings.description) %></p>
        <div class="rate-project">    
          <%= rating_for project, :rating, disable_after_rate: false, enable_half: true, cancel: false %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<section id="slider">
  <div id="home-carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag @home.images.first.image.url, class: "resize-slide" %>
        <div class="carousel-caption container">
          <div class="row">
            <div class="col-sm-7">
              <h2 id = "home-title"><%= @home.title %></h2>
              <h3 id = "home-sologan"><%= @home.sologan %></h3>
              <p id = "home-description"><%= @home.description %></p>
            </div>
          </div>
        </div>
      </div>
      <% @home.images[Settings.array_image.second..Settings.array_image.last]
        .each do |image, i| %>
        <div class="item">
          <%= image_tag image.image.url, class: "resize-slide" %>
          <div class="carousel-caption container">
            <div class="row">
              <div class="col-sm-7">
                <h2 id = "home-title"><%= @home.title %></h2>
                <h3 id= "home-sologan"><%= @home.sologan %></h3>
                <p id = "home-description"><%= @home.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <a class="home-carousel-left" href="#home-carousel" data-slide="prev">
        <i class="fa fa-angle-left"></i>
      </a>
      <a class="home-carousel-right" href="#home-carousel" data-slide="next">
        <i class="fa fa-angle-right"></i>
      </a>
    </div>
  </div>
</section>
<section id="our-works">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-title">
          <h1 class="font-family"><%= t "manage.our_project" %></h1>
          <span class="st-border"></span>
        </div>
      </div>
      <div class="portfolio-wrapper" >
        <div class="portfolio-items">
        <%= render "list_project" %>
        </div>
      </div>
    </div>
    <%= link_to t("read_more"), projects_path, class: "btn btn-send margin-45" %>
  </div>
</section>
<section id="about-us">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <div class="about-us text-center">
          <h4><%= t "question.title_1" %><br/><%= t "question.title_2" %></h4>
          <p>
            <%= t "question.description" %>
          </p>
          <hr />
        </div>
      </div>
      <div class="col-sm-6 our-office">
        <div id="office-carousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="item active resize-culture">
              <%= image_tag "/assets/cultural/vanhoa-2.jpg" %>
            </div>
            <div class="item resize-culture">
              <%= image_tag "/assets/cultural/vanhoa-2.jpg" %>
            </div>
            <div class="item resize-culture">
              <%= image_tag "/assets/cultural/vanhoa-2.jpg" %>
            </div>
            <div class="item resize-culture">
              <%= image_tag "/assets/cultural/vanhoa-2.jpg" %>
            </div>
            <div class="item resize-culture">
              <%= image_tag "/assets/cultural/vanhoa-2.jpg" %>
            </div>
            <a class="office-carousel-left" href="#office-carousel" data-slide="prev">
              <i class="fa fa-angle-left"></i>
            </a>
            <a class="office-carousel-right" href="#office-carousel" data-slide="next">
              <i class="fa fa-angle-right"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="introduce-team">
  <div class="container">
    <div class="row">
      <div class="overlay"></div>
      <div class="col-md-8 col-md-offset-2 col-sm-12">
        <div class="st-introduce-teams">
          <div id="fade-quote-carousel" class="carousel slide owl-wrapper" data-ride="carousel" data-interval="3000">
            <ol class="carousel-indicators">
              <li data-target="#fade-quote-carousel" data-slide-to="0"></li>
              <li data-target="#fade-quote-carousel" data-slide-to="1"></li>
              <li data-target="#fade-quote-carousel" data-slide-to="2" class="active"></li>
              <li data-target="#fade-quote-carousel" data-slide-to="3"></li>
              <li data-target="#fade-quote-carousel" data-slide-to="4"></li>
            </ol>
            <div class="carousel-inner">
              <div class="active item">
                <div class="profile-circle left member1"></div>
                <blockquote>
                  <p><%= t "list_team.speak1" %></p>
                <div class="st-border"></div>
                <div class="client-info">
                  <h5><%= t "list_team.member1" %></h5>
                  <span><%= t "position.manage" %></span>
                </div>
                </blockquote>
                <div class="clear"></div>
              </div>
              <div class="item">
                <div class="profile-circle left member2"></div>
                <blockquote>
                  <p><%= t "list_team.speak1" %></p>
                <div class="st-border"></div>
                <div class="client-info">
                  <h5><%= t "list_team.member2" %></h5>
                  <span><%= t "position.manage" %></span>
                </div>
                </blockquote>
              </div>
              <div class="item">
                <div class="profile-circle left member2"></div>
                <blockquote>
                  <p><%= t "list_team.speak1" %></p>
                <div class="st-border"></div>
                <div class="client-info">
                  <h5><%= t "list_team.member3" %></h5>
                  <span><%= t "position.dev" %></span>
                </div>
                </blockquote>
              </div>
              <div class="item">
                <div class="profile-circle left member2"></div>
                <blockquote>
                  <p><%= t "list_team.speak1" %></p>
                <div class="st-border"></div>
                <div class="client-info">
                  <h5><%= t "list_team.member4" %></h5>
                  <span><%= t "position.dev" %></span>
                </div>
                </blockquote>
              </div>
              <div class="item">
                <div class="profile-circle left member2"></div>
                <blockquote>
                  <p><%= t "list_team.speak1" %></p>
                <div class="st-border"></div>
                <div class="client-info">
                  <h5><%= t "list_team.member5" %></h5>
                  <span><%= t "position.dev" %></span>
                </div>
                </blockquote>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>
<section id="fun-facts">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3">
        <div class="fun-fact text-center">
          <h3>
            <i class="fa fa-thumbs-o-up"></i>
            <span class="st-counter"><%= User.count %></span>
          </h3>
          <p><%= t "employee" %></p>
        </div>
      </div>
      <div class="col-sm-6 col-md-3">
        <div class="fun-fact text-center">
          <h3><i class="fa fa-briefcase fa-6"></i> <span class="st-counter"><%= Project.count %></span></h3>
          <p><%= t "complete_project" %></p>
        </div>
      </div>
      <div class="col-sm-6 col-md-3">
        <div class="fun-fact text-center">
          <h3><i class="fa fa-code"></i> <span class="st-counter"><%= Post.news.count %></span></h3>
          <p><%= t "news" %></p>
        </div>
      </div>
      <div class="col-sm-6 col-md-3">
        <div class="fun-fact text-center">
          <h3><i class="fa fa-coffee"></i> <span class="st-counter"><%= Post.blog.count %></span></h3>
          <p><%= t "blogs.name" %></p>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render "contacts/contact" %>