config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", as: "rate"
  devise_for :users, controllers: {omniauth_callbacks: "callbacks",
    registrations: "users"}

  scope "(:locale)", locale: /en|vi|ja/ do
    root "static_pages#home"

    resources :users
    resources :blogs
    resources :news
    resources :likes
    resources :comments
    resources :contacts
    resources :categories
    resources :like_blogs
    resources :projects do
      resources :participates
    end
    namespace :admin do
      root "admin#index"
      resources :homes
      resources :users
      resources :projects do
        resources :participates
      end
    end
    resources :messages
  end

  mount ActionCable.server => "/cable"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    if user && (user.has_role? User::ROLES[:admin])
      can :manage, :all
      can [:update, :destroy, :new], [Post, Project]
    else
      can :manage, [Post, Project]
      can :read, :all
    end
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :post
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :projects, dependent: :destroy

  enum target_type: {blog: 0, news: 1, project: 2}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :target, polymorphic: true

  scope :order_by_newest, ->{order created_at: :desc}
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true,
   length: {maximum: Settings.contact.name_length}
  validates :email, presence: true,
   length: {maximum: Settings.contact.email_length}
  validates :title, presence: true,
   length: {maximum: Settings.contact.title_length}
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :project
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :images, as: :target

  accepts_nested_attributes_for :images, allow_destroy: true

  enum language: {en: 0, vi: 1, ja: 2}
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :target, polymorphic: true

  mount_uploader :image, ImageUploader,
    reject_if: proc{ |param| param[:image].blank? && param[:image_cache].blank? &&
    param[:id].blank? }, allow_destroy: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :project

  after_create_commit {MessageBroadcastJob.perform_now self}
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user_create, class_name: User.name
  belongs_to :user
  belongs_to :notificationable, polymorphic: true

  scope :order_by_newest, ->{order created_at: :desc}
  scope :uncheck, ->{where(checked: false).count}
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :user
  belongs_to :project

  scope :accepted, ->{where is_accept: true}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :attachments, dependent: :destroy
  has_many :likes, as: :target
  has_many :comments, as: :target
  has_many :notifications, as: :notificationable

  mount_uploader :image, ImageUploader

  delegate :name, to: :category, prefix: :category, allow_nil: true
  delegate :name, to: :user, prefix: :user, allow_nil: true

  validates :title, presence: true
  validates :content, presence: true

  enum target_type: {blog: 0, news: 1}

  scope :order_by_newest, ->{order created_at: :desc}
  scope :post_by_category_and_type, -> category_id, target_type do
    where category: category_id, target_type: target_type
  end
  scope :except_id, ->id do
    where("id != ?", id).limit Settings.related_item
  end

  ratyrate_rateable :rating
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  has_many :feedbacks, dependent: :destroy
  has_many :participates, dependent: :destroy
  has_many :users, through: :participates
  has_many :messages, dependent: :destroy
  has_many :likes, as: :target
  has_many :images, as: :target
  has_many :targettechniques, as: :target
  has_many :comments, as: :target

  scope :order_by_newest, ->{order created_at: :desc}

  accepts_nested_attributes_for :images, allow_destroy: true


  validates :name, presence: true,
   length: {maximum: Settings.project.name_length}
  validates :url, presence: true,
   length: {maximum: Settings.project.url_length}
  validates :description, presence: true,
   length: {maximum: Settings.project.description_length}
  validates :realease_note, presence: true,
   length: {maximum: Settings.project.realease_note_length}
  validates :git_repository, presence: true,
   length: {maximum: Settings.project.git_repository_length}
  validates :server_information, presence: true,
   length: {maximum: Settings.project.server_information_length}
  validates :platform, presence: true,
   length: {maximum: Settings.project.platform_length}
  validates :core_features, presence: true,
   length: {maximum: Settings.project.core_features_length}
  validates :pm_url, presence: true,
   length: {maximum: Settings.project.pm_url_length}

  ratyrate_rateable :rating

  PRIVATE_ATTRIBUTES = {server_information: "server_information",
    git_repository: "git_repository", pm_url: "pm_url"}

  BRANCH = [[Settings.branch.hanoi, 0],[Settings.branch.danang, 1]]
  private

  def check_max_files
    if images.blank? || images.size > Settings.project.max_image_files
      errors.add(:dagger, I18n.t("projects.check_max_files"))
    end
  end

  def self.show_for_rating
    Project.all.sort_by {|u| [u.average(:rating) ? u.average(:rating).avg : 0, u.average(:rating)]}.reverse
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource, polymorphic: true, optional: true

  validates :resource_type, inclusion: {in: Rolify.resource_types}, allow_nil: true

  scopify
end

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :user
end

app/models/technique.rb
class Technique < ApplicationRecord
  has_many :target_techniques, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, omniauth_providers: [:facebook, :twitter]

  has_many :socials, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :participates, dependent: :destroy
  has_many :projects, through: :participates
  has_many :techniques, through: :target_techniques
  has_many :messages, dependent: :destroy
  has_many :certificate_users, dependent: :destroy
  has_many :certifications, through: :certificate_users
  has_many :likes, as: :target
  has_many :target_techniques, as: :target
  has_many :notifications, dependent: :destroy

  mount_uploader :avatar, ImageUploader
  mount_uploader :cover_photo, ImageUploader

  ROLES = {admin: "Admin", user: "User"}

  validates :name, presence: true, length: {maximum: Settings.user.name}

  scope :order_by_newest, ->{order created_at: :desc}
  scope :member_not_in_project, lambda { |ids| where(["id NOT IN (?)", ids]) if ids.any? }

  ratyrate_rateable :rating

  ratyrate_rater

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name unless auth.info.name.nil?
      user.email = auth.info.email unless auth.info.email.nil?
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/views/shared/_contact_form.html.erb
<!-- CONTACT -->
<section id="contact" class="padding-top-40">
  <div class="contact">
    <div class="row">
      <div class="col-md-12">
        <div class="section-title">
          <h1 class="font-family"><%= t("contact_us") %></h1>
          <span class="st-border"></span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 contact-info wow fadeInLeft">
        <p class="contact-content"><%= t("contact_detail") %></p>
        <p class="st-address"><i class="fa fa-map-marker"></i><strong><%= t("contact_address") %></strong></p>
        <p class="st-phone"><i class="fa fa-mobile"></i><strong><%= Settings.contact_phone %></strong></p>
        <p class="st-email"><i class="fa fa-envelope-o"></i><strong><%= Settings.contact_mail %></strong></p>
        <p class="st-website"><i class="fa fa-globe"></i><strong><%= Settings.contact_domain %></strong></p>
      </div>
      <div class="col-sm-7 col-sm-offset-1">
        <%= form_for @contact do |f| %>
        <%= render "shared/error_messages", object: @contact %>
          <div class="row">
            <% if current_user.present? %>
              <div class="col-sm-6">
                <%= f.text_field :name, value: current_user.name, class: "form-control", placeholder: t("name") %>
              </div>
              <div class="col-sm-6">
                <%= f.email_field :email, value: current_user.email, class: "form-control", placeholder: t("email") %>
              </div>
            <% else %>
              <div class="col-sm-6">
                <%= f.text_field :name, class: "form-control", placeholder: t("name") %>
              </div>
              <div class="col-sm-6">
                <%= f.email_field :email, class: "form-control", placeholder: t("email") %>
              </div>
            <% end %>
            <div class="col-sm-12">
              <%= f.label :title %>
              <%= f.text_field :title, class: "form-control" %>
            </div>
            <div class="col-sm-12">
              <%= f.label :content %>
              <%= f.text_area :content, class: "form-control height-200-px" %>
            </div>
            <div class="col-sm-12">
              </br>
              <%= f.submit (t "send_message"), class: "btn btn-send" %>
            </div>
          </div>
        <% end %>
        </br>
        <div id="map"></div>
      </div>
    </div>
  </div>
</section>
<script src="<%= @key %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<!-- /CONTACT -->

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "message" %>
      <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.js.erb
<% flash.each do |key, value| %>
  <% case key %>
  <% when Settings.message_notice %>
    <script>
      $.growl.notice({title: "", message: "<%= value %>"});
    </script>
  <% when Settings.message_alert %>
    <script>
      $.growl.error({title: "", message: "<%= value %>"});
    </script>
  <% when Settings.message_danger %>
    <script>
      $.growl.error({title: "", message: "<%= value %>"});
    </script>
  <% else %>
    <script>
      $.growl.warning({title: "", message: "<%= value %>"});
    </script>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
<% if user_signed_in? %>
  <%= link_to "#{t ("like_button")} #{image_tag("like-down.png", class: "like-button")}"
    .html_safe, likes_path(id: project.id, locale: I18n.locale), method: :post,
    class: "btn btn-default stat-item active", id: "like-post", remote: true %>
<% else %>
  <%= link_to "#{t ("like_button")} #{image_tag("like-down.png", class: "like-button")}"
  .html_safe, likes_path(id: project.id, locale: I18n.locale), method: :post,
  class: "btn btn-default stat-item active", id: "like-post" %>
<% end %>

app/views/shared/_like_blog.html.erb
<div class="like-unlike-form-div-blog" id="like-unlike-form-div-blog<%= blog.id %>">
  <% if @like.present? %>
    <%= render "like_blogs/unlike", blog: blog %>
  <% else %>
    <%= render "like_blogs/like", blog: blog %>
  <% end %>
</div>
<div class="like-count-div-blog">
  <span class="like-count" id="like-count-blog<%= blog.id %>">
    <%= blog.likes.count %>
  </span>
  <%= t "liked" %>
</div>

app/views/shared/_like_project.html.erb
<div class="like-unlike-form-div" id="like-unlike-form-div-<%= project.id %>">
  <% if @like.present? %>
    <%= render "shared/unlike", project: project %>
  <% else %>
    <%= render "shared/like", project: project %>
  <% end %>
</div>
</br>
<div class="like-count-div">
  <span class="like-count" id="like-count-<%= project.id %>"> 
    <%= project.likes.count %>
  </span>
  <%= t "liked" %>
</div>

app/views/shared/_list_user.html.erb
<div class="container ">
  <% if @users.present? %>
    <% if @project %>
      <%= search_form_for @t, url: project_participates_path(I18n.locale, @project),
       id: "search_form", class: " margin-top-null" do |f| %>
        <div class="ui input icon search-form">
          <%= f.search_field :name_or_email_cont, placeholder: "Find by name or email",
            id: "user_search" %>
        </div>
        <%= f.submit (t "search_button"), class: "ui blue button" %>
      <% end %>
      <div class="ui link cards" id= "users-<%= @project.id %>">
    <% else %>
      <%= search_form_for @q, id: "search_form" do |f| %>
        <div class="ui input icon search-form">
          <%= f.search_field :name_or_email_cont, placeholder: "Find by name or email",
            id: "user_search" %>
        </div>
        <%= f.submit (t "search_button"), class: "ui blue button" %>
      <% end %>
      <div class="ui link cards" id= "users">
    <% end %>
      <%= render @users %>
    </div>

    <center>
      <%= link_to_next_page @users, (t "load_more"), remote: true, id: "load_more",
        class: "btn btn-primary" %>
    </center>
  <% else %>
    <p><%= t ".no_user_found" %> <%= params[:search] %>.</p>
  <% end %>
</div>

app/views/shared/_unlike.html.erb
<% if user_signed_in? %>
  <%= link_to "#{t ("like_button")} #{image_tag("like-up.png", class: "like-button")}"
    .html_safe, like_path(id: project.id, locale: I18n.locale), method: :delete,
    class: "btn btn-default stat-item active", id: "like-post", remote: true %>
<% else %>
  <%= link_to "#{t ("like_button")} #{image_tag("like-up.png", class: "like-button")}"
  .html_safe, like_path(id: project.id, locale: I18n.locale), method: :delete,
  class: "btn btn-default stat-item active", id: "like-post" %>
<% end %>

app/views/shared/_user_form.html.erb
<div class="col-md-12">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for [:admin, @user] do |f| %>
      <%= render "shared/error_messages",object: @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      </br>
      <center><%= f.submit "Save", class: "add-account-button" %></center>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>