config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", as: "rate"
  devise_for :users, controllers: {omniauth_callbacks: "callbacks",
    registrations: "users"}

  scope "(:locale)", locale: /en|vi|ja/ do
    root "static_pages#home"

    resources :users
    resources :blogs
    resources :news
    resources :likes
    resources :comments
    resources :contacts
    resources :categories
    resources :like_blogs
    resources :projects do
      resources :participates
    end
    namespace :admin do
      root "admin#index"
      resources :homes
      resources :users
      resources :projects do
        resources :participates
      end
    end
    resources :messages
  end

  mount ActionCable.server => "/cable"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  has_many :feedbacks, dependent: :destroy
  has_many :participates, dependent: :destroy
  has_many :users, through: :participates
  has_many :messages, dependent: :destroy
  has_many :likes, as: :target
  has_many :images, as: :target
  has_many :targettechniques, as: :target
  has_many :comments, as: :target

  scope :order_by_newest, ->{order created_at: :desc}

  accepts_nested_attributes_for :images, allow_destroy: true


  validates :name, presence: true,
   length: {maximum: Settings.project.name_length}
  validates :url, presence: true,
   length: {maximum: Settings.project.url_length}
  validates :description, presence: true,
   length: {maximum: Settings.project.description_length}
  validates :realease_note, presence: true,
   length: {maximum: Settings.project.realease_note_length}
  validates :git_repository, presence: true,
   length: {maximum: Settings.project.git_repository_length}
  validates :server_information, presence: true,
   length: {maximum: Settings.project.server_information_length}
  validates :platform, presence: true,
   length: {maximum: Settings.project.platform_length}
  validates :core_features, presence: true,
   length: {maximum: Settings.project.core_features_length}
  validates :pm_url, presence: true,
   length: {maximum: Settings.project.pm_url_length}

  ratyrate_rateable :rating

  PRIVATE_ATTRIBUTES = {server_information: "server_information",
    git_repository: "git_repository", pm_url: "pm_url"}

  BRANCH = [[Settings.branch.hanoi, 0],[Settings.branch.danang, 1]]
  private

  def check_max_files
    if images.blank? || images.size > Settings.project.max_image_files
      errors.add(:dagger, I18n.t("projects.check_max_files"))
    end
  end

  def self.show_for_rating
    Project.all.sort_by {|u| [u.average(:rating) ? u.average(:rating).avg : 0, u.average(:rating)]}.reverse
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_project, only: [:edit, :update]
  load_and_authorize_resource

  def new
    @categories = Category.all
    @project = Project.new
    @project.images.build
  end

  def index
    @q = Project.ransack params[:q]
    @projects = Kaminari.paginate_array(@q.result.show_for_rating)
      .page(params[:page]).per(Settings.per_page.projects)
    @categories = Category.all
  end

  def create
    @project = current_user.projects.new project_params
    check_private_attributes
    if current_user.save
      flash[:success] = t "projects.created"
      redirect_to admin_project_participates_path(I18n.locale, @project)
    else
      @categories = Category.all
      flash[:danger] = t "images.create_failed"
      render :new
    end
  end

  def show
    @project = Project.find_by id: params[:id]
    @message = Message.new
    if @project
      @support = Supports::ProjectSupport.new(@project)
      @comments = @support.comments.order_by_newest
        .page(params[:page]).per Settings.per_page.comment
      respond_to do |format|
        format.html
        format.js
      end
    else
      flash[:warning] = t "record_isnt_exist"
      redirect_to root_url
    end
  end

  def edit
  end

  def update
    @project.update_attributes project_params
    if @project.save
      flash[:success] = t "succeed"
      redirect_to project_path(I18n.locale, @project)
    else
      render :edit
    end

  end

  private
  def check_private_attributes
    private_value = Array.new
    Project::PRIVATE_ATTRIBUTES.each do |key, value|
      if params[key] == Settings.private
        private_value.push value
      end
    end
    @project.private_attributes = private_value.join(",")
  end

  def load_project
    @project = Project.find_by id: params[:id]
    unless @project
      flash[:danger] = t "project_not_found"
      redirect_to root_url
    end
  end

  def project_params
    params.require(:project).permit :name, :url, :description, :core_features, :pm_url,
      :realease_note, :git_repository, :server_information, :platform, :category_id,
      :pm_url, images_attributes: [:id, :image, :image_cache, :_destroy]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_project, only: [:edit, :update]
  load_and_authorize_resource

  def new
    @categories = Category.all
    @project = Project.new
    @project.images.build
  end

  def index
    @q = Project.ransack params[:q]
    @projects = Kaminari.paginate_array(@q.result.show_for_rating)
      .page(params[:page]).per(Settings.per_page.projects)
    @categories = Category.all
  end

  def create
    @project = current_user.projects.new project_params
    check_private_attributes
    if current_user.save
      flash[:success] = t "projects.created"
      redirect_to project_participates_path(I18n.locale, @project)
    else
      @categories = Category.all
      flash[:danger] = t "images.create_failed"
      render :new
    end
  end

  def show
    @project = Project.find_by id: params[:id]
    @message = Message.new
    if @project
      @support = Supports::ProjectSupport.new(@project)
      @comments = @support.comments.order_by_newest
        .page(params[:page]).per Settings.per_page.comment
      respond_to do |format|
        format.html
        format.js
      end
    else
      flash[:warning] = t "record_isnt_exist"
      redirect_to root_url
    end
  end

  def edit
  end

  def update
    @project.update_attributes project_params
    if @project.save
      flash[:success] = t "succeed"
      redirect_to project_path(I18n.locale, @project)
    else
      render :edit
    end

  end

  private
  def check_private_attributes
    private_value = Array.new
    Project::PRIVATE_ATTRIBUTES.each do |key, value|
      if params[key] == Settings.private
        private_value.push value
      end
    end
    @project.private_attributes = private_value.join(",")
  end

  def load_project
    @project = Project.find_by id: params[:id]
    unless @project
      flash[:danger] = t "project_not_found"
      redirect_to root_url
    end
  end

  def project_params
    params.require(:project).permit :name, :url, :description, :core_features, :pm_url,
      :realease_note, :git_repository, :server_information, :platform, :category_id,
      :pm_url, images_attributes: [:id, :image, :image_cache, :_destroy]
  end
end

app/helpers/project_helper.rb
module ProjectHelper

  def set_class_by_index index
    "active" if index == 0
  end
end

app/views/admin/projects/_image_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache, value: f.object.image_cache %>
  </td>
  <td class="thumb">
    <% if f.object.image.url.present? %>
      <%= image_tag f.object.image.url %>
    <% end %>
  </td>
  <td>
    <%= link_to_remove_association (t "remove"), f %>
  </td>
</tr>

app/views/admin/projects/_member_of_project.html.erb
<% @support.participates.each do |participate| %>
  <div class="col-md-3 margin-top-20">
    <div class="left">
      <%= link_to user_path(I18n.locale, participate) do %>
        <%= image_tag participate.user.avatar.url,
          class: "img-member-of-project" %>
      <% end %>
    </div>
    <div class="left item-member-project">
      <%= link_to "#{participate.user.name}", user_path(I18n.locale, participate),
        title: "#{participate.user.name}" %><br/>
      <span><%= participate.position %></span>
    </div>
  </div>
<% end %>

app/views/admin/projects/_project.html.erb
<div class="col-md-4 col-sm-6 work-grid wordpress graphic">
  <div class="portfolio-content">
    <%= link_to project_path(I18n.locale, project), class: "img-responsive" do %>
      <%= image_tag project.images.first.image.url, class: "img-responsive resize-project" %>
    <% end %>
    <div class="portfolio-overlay">
      <%= link_to project_path(I18n.locale, project) do %><i class="fa fa-camera-retro"></i><% end %>
      <h5><%= project.name %></h5>
      <p><%= project.description.truncate(Settings.description) %></p>
      <div class="rate-project">    
        <%= rating_for project, :rating, disable_after_rate: false, enable_half: true, cancel: false %>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/edit.html.erb
<section id="page-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-title">
          <h1><%= t "edit_project" %></h1>
          <span class="st-border"></span>
        </div>
      </div>
    </div>
  </div>
</section>
<%= form_for @project, url: project_path, html: {method: :put} do |f| %>
  <%= render "shared/error_messages", object: @project %>
  <section id="project">
    <div class="container edit_project">
      <div class="row">
        <div class="col-md-12">
          <div class="single-blog">
            <article>
              <div class="post-article">
                <div class="col-md-6 margin-20">
                  <p class="text-left">
                  <b> <%= t "name" %>: </b><br />
                    <%= f.text_field :name, class: "form-control input-md",
                      required: true %>
                  </p>
                </div>
                <div class="col-md-6 margin-20">
                  <p class="text-left">
                  <b> <%= t "description" %>: </b><br />
                    <%= f.text_field :description, class: "form-control input-md",
                      required: true %>
                  </p>
                </div>
                <br />
                <div class="col-md-6">
                  <p class="text-left">
                  <b> <%= t "realease_note" %>: </b><br />
                    <%= f.text_field :realease_note, class: "form-control input-md",
                      required: true %>
                  </p>
                </div>
                <% Project::PRIVATE_ATTRIBUTES.each do |key, value| %>
                  <div class="col-md-6">
                    <p class="text-left">
                    <b> <%= key %> : <%= radio_button_tag key, Settings.public %>
                    <%= t "public" %>
                    <%= radio_button_tag key, Settings.private, checked: true %>
                    <%= t "private" %></b><br />
                    <%= f.text_field key, class: "form-control input-md", required: true %></p>
                  </div>
                <% end %>
                <div class="col-md-6">
                  <p class="text-left">
                  <b> <%= t "core_features" %>: </b><br />
                    <%= f.text_field :core_features, class: "form-control input-md",
                      required: true %>
                  </p>
                </div>
                <div class="col-md-6">
                  <p class="text-left">
                  <b> <%= t "platform" %>: </b><br />
                    <%= f.text_field :platform, class: "form-control input-md",
                      required: true %>
                  </p>
                </div>
                <div class="col-md-6">
                  <p class="text-left">
                  <b> <%= t "url" %>: </b><br />
                    <%= f.text_field :url, class: "form-control input-md",
                      required: true %>
                  </p>
                </div>
                <div class="col-md-6">
                  <p class="text-left">
                  <b> <%= t "realease_note" %>: </b><br />
                    <%= f.text_field :realease_note, class: "form-control input-md",
                      required: true %>
                  </p>
                </div>
                <div class="form-group">
                  <div class="col-md-6">
                    <table class="user-photo-form">
                      <%= f.fields_for :images do |image| %>
                        <%= render "image_fields", f: image %>
                      <% end %>
                      <%= link_to_add_association (t "add_a_photo"),
                       f, :images, class: "btn btn-warning" %>
                    </table>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="button-edit">
                  <%= f.submit t("save"), class: "btn btn-success" %>
                  <%= link_to t("cancel"), project_path(I18n.locale, @project),
                    class: "btn btn-default" %>
                </div>
              </div>
            </article>
          </div>
          <hr>
          <br/ >
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/admin/projects/new.html.erb
<h3>Thêm dự án  </h3>
<%= form_for [:admin, @project], html: {class: "form-horizontal "} do |f| %>
  <%= render "shared/error_messages", object: @project %>
  <fieldset>
    <div class="form-group">
      <%= f.label :name, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_field :name, class: "form-control input-md",
          placeholder: true, required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :url, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.url_field :url, class: "form-control input-md",
          placeholder: true, required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :core_features, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_field :core_features, class: "form-control input-md",
          placeholder: true, required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :platform, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_field :platform, class: "form-control input-md",
          placeholder: true, required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>

    <% Project::PRIVATE_ATTRIBUTES.each do |key, value| %>
      <div class="form-group">
        <%= f.label key, class: "col-md-4 control-label" %>
        <div class="col-md-4">
          <%= f.text_field key, class: "form-control input-md",
            placeholder: true, required: true %>
          <%= radio_button_tag key, Settings.public %>
          <%= t "public" %>
          <%= radio_button_tag key, Settings.private, checked: true %>
          <%= t "private" %>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :realease_note, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_field :realease_note, class: "form-control input-md",
         placeholder: true, required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :category, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.select :category_id, options_for_select(@categories.all.map{|c| [c.name, c.id]},
          f.object.category_id), {},
          {class: "form-control selectpicker", "data-live-search": true} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :images, class: "col-md-4 control-label"%>
      <div class="col-md-4">
        <table class="user-photo-form">
          <%= f.fields_for :images do |image| %>
            <%= render "image_fields", f: image %>
          <% end %>
          <%= link_to_add_association (t "add_a_photo"), f, :images, class: "btn btn-default" %>
        </table>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-4 control-label" for="save"></label>
      <div class="col-md-8">
        <%= f.submit t("save") , class: "btn btn-primary" %>
        <%= button_tag t(".reset"), type: :reset, class: "btn btn-inverse"%>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/admin/projects/show.html.erb
<section id="page-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-title">
          <div>
            <div class="left">
              <h2 class="font-size-40"><%= @project.name %></h2>
              <div class="disable-cancela">
                <%= rating_for @project, :rating, disable_after_rate: false, enable_half: true, cancel: false %>
              </div>
              </br>
            </div>
            <div class="right">
              <div class="slideouticons">
                <input type="checkbox" id="togglebox" />
                <label for="togglebox" class="mainlabel fa fa-share-alt"></label>
                <div class="iconswrapper">
                  <% if user_signed_in? %>
                    <ul>
                      <li>
                        <%= link_to "", edit_project_path(I18n.locale, @project),
                          class: "fa fa-pencil-square-o", title: t("edit_project") %>
                      </li>
                      <li>
                        <%= link_to "", project_participates_path(I18n.locale, @project),
                          class: "fa fa-plus-square", title: t("add_member_project") %>
                      </li>
                      <li>
                        <%= link_to "", "", class: "fa fa-trash-o", title: t("delete_project") %>
                      </li>
                    </ul>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="clear"></div>
          </div>
          <div class="post-meta text-uppercase">
            <span><%= @project.created_at %></span>
            <span><%= t "in" %> <%= link_to @project.category.name, "" %></span>
          </div>
          <button class="ui facebook button">
            <i class="facebook icon"></i>
            <%= t "facebook" %>
          </button>
          <button class="ui twitter button">
            <i class="twitter icon"></i>
            <%= t "twitter" %>
          </button>
          <button class="ui google plus button">
            <i class="google plus icon"></i>
            <%= t "google_plus" %>
          </button>
          <button class="ui vk button">
            <i class="vk icon"></i>
            <%= t "vk" %>
          </button>
          <button class="ui linkedin button">
            <i class="linkedin icon"></i>
            <%= t "linkedin" %>
          </button>
          <button class="ui instagram button">
            <i class="instagram icon"></i>
            <%= t "instagram" %>
          </button>
          <button class="ui youtube button">
            <i class="youtube icon"></i>
            <%= t "youtube" %>
          </button>
          <span class="st-border"></span>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="project">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div>
          <article>
            <div class="post-thumb">
                <div class="vc_single_image-wrapper   vc_box_border_grey">
                  <div id="portfolio_slide" class="carousel slide"
                    data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                      <% @support.images.each_with_index do |image, index| %>
                        <div class="item <%= set_class_by_index index %>">
                            <%= image_tag image.image.url ,
                              class: "img-responsive img-centered
                            img-slide img-project" %>
                        </div>
                      <% end %>
                      <ol class="carousel-indicators">
                        <% @support.images.each_with_index do |image, index| %>
                          <li data-target="#portfolio_slide"
                            data-slide-to=<%= index %>
                            class="<%= set_class_by_index index %>">
                          </li>
                        <% end %>
                      </ol>
                    </div>
                  </div>
                </div>
            </div>
          </article>
        </div>
        <hr>
        <br/ >
      </div>
      <div class="col-md-4">
        <div class="row info-project">
          <div class="col-md-12">
            <span class="feature-project">
            </span><p id="project-description"><%= @project.description %></p>
          </div>
          <div class="col-md-12 padding-top-10">
            <p class="text-left">
              <span class="glyphicon glyphicon glyphicon-th-large gold"></span>
              <b> <%= t "server_informations" %>: </b><br />
              <%= @project.server_information %>
            </p>
          </div>
          <div class="col-md-12 padding-top-10">
            <p class="text-left">
              <span class="glyphicon glyphicon-star gold"></span>
              <b> <%= t "core_features" %>: </b><br />
              <%= @project.core_features %>
            </p>
          </div>
          <div class="col-md-12 padding-top-10">
            <p class="text-left">
              <span class="glyphicon glyphicon-list-alt gold"></span>
              <b> <%= t "platform" %>: </b><br />
              <%= @project.platform %>
            </p>
          </div>
          <div class="col-md-12 padding-top-10">
            <p class="text-left">
              <span class="glyphicon glyphicon-cloud gold"></span>
              <b> <%= t "url" %>: </b><br />
              <%= link_to @project.url, @project.url %>
            </p>
          </div>
          <div class="col-md-12 padding-top-10">
            <p class="text-left">
              <span class="glyphicon glyphicon-globe gold"></span>
              <b> <%= t "pm_url" %>: </b><br />
              <%= link_to @project.pm_url, @project.pm_url %>
            </p>
          </div>
          <div class="col-md-12 padding-top-10">
            <p class="text-left">
              <span class="glyphicon glyphicon-star gold"></span>
              <b> <%= t "git_repository" %>: </b><br />
              <%= link_to @project.git_repository, @project.git_repository %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="row margin-bottom-50">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active">
            <%= link_to t("member_of_project") , "#member_of_project", data: {toggle: "tab"} %>
          </li>
          <li class="">
            <%= link_to t("comments"), "#comment", data: {toggle: "tab"} %>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="member_of_project">
            <div class="row margin-bottom-50">
              <%= render "member_of_project", object: @project.users %>
            </div>
          </div>
          <div class="tab-pane" id="comment">
            <div class="row margin-bottom-50">
              </br>
              <%= render partial: "comments/comment_form", locals: {project: @project}%>
            </div>
            <div class="entries" id="entries">
            <%= render @comments %>
          </div>
          <center>
            <%= link_to_next_page @comments, (t "load_more"), remote: true,
             id: "load_more",class: "btn btn-primary" %>
           </center>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="panel panel-chat panel-default">
      <div class="panel-heading">
        <a href="#" id="chatMinimize" onclick="return false"><span>
          <%= t "chat_box" %></span></a>
        <a href="#" id="chatClose" onclick="return false">
          <i class="glyphicon glyphicon-remove"></i></a>
        <div class="clearFix"></div>
      </div>
      <% if @project.messages.any? %>
        <div class="panel-body msg_container_base" id="messages" data-chatroom= <%= @project.id %> >
          <%= render @project.messages %>
        </div>
      <% else %>
        <div class="panel-body hidden" id="messages" data-chatroom= <%= @project.id %> ></div>
      <% end %>
      <div class="panel-footer">
        <%= render partial: "messages/message_form",
          locals: {message: @message, project: @project} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/show.js.erb
$('#entries').append("<%= j (render partial: @comments)%>");
$('#load_more').replaceWith("<%= j (link_to_next_page(@comments, (t 'load_more'), remote: true, id: 'load_more', class: 'btn btn-primary'))%>")