config/routes.rb
Rails.application.routes.draw do
  post "/rate" => "rater#create", as: "rate"
  devise_for :users, controllers: {omniauth_callbacks: "callbacks",
    registrations: "users"}

  scope "(:locale)", locale: /en|vi|ja/ do
    root "static_pages#home"

    resources :users
    resources :blogs
    resources :news
    resources :likes
    resources :comments
    resources :contacts
    resources :categories
    resources :like_blogs
    resources :projects do
      resources :participates
    end
    namespace :admin do
      root "admin#index"
      resources :homes
      resources :users
      resources :projects do
        resources :participates
      end
    end
    resources :messages
  end

  mount ActionCable.server => "/cable"
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :user
  belongs_to :project

  scope :accepted, ->{where is_accept: true}
end

app/controllers/admin/participates_controller.rb
class Admin::ParticipatesController < Admin::AdminController
  before_action :authenticate_user!
  before_action :load_project, only: [:create, :index, :destroy]
  before_action :load_participate, only: [:destroy, :show]
  load_and_authorize_resource

  def index
    @t = User.member_not_in_project(@project.participates.pluck :user_id).ransack params[:t]
    @users = @t.result.page(params[:page]).per Settings.per_page.user
    @participates = @project.participates
  end

  def new
  end

  def create
    @participate = Participate.new participate_params
    @participate.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @participate.destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def participate_params
    params.require(:participate).permit(:position, :user_id, :project_id)
      .merge is_accept: true
  end

  def load_project
    @project = Project.find_by id: params[:project_id]
    unless @project
      flash[:danger] = t "project_not_found"
      redirect_to root_url
    end
  end

  def load_participate
    @participate = Participate.find_by id: params[:id]
    unless @participate
      flash[:danger] = t "user_not_found"
      redirect_to root_url
    end
  end
end

app/controllers/participates_controller.rb
class ParticipatesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_project, only: [:create, :index, :destroy]
  before_action :load_participate, only: [:destroy, :show]
  def index
    @t = User.member_not_in_project(@project.participates.pluck :user_id).ransack params[:t]
    @users = @t.result.page(params[:page]).per Settings.per_page.user
    @participates = @project.participates
  end

  def new
  end

  def create
    @participate = Participate.new participate_params
    @participate.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @participate.destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def participate_params
    params.require(:participate).permit(:position, :user_id, :project_id)
      .merge is_accept: true
  end

  def load_project
    @project = Project.find_by id: params[:project_id]
    unless @project
      flash[:danger] = t "project_not_found"
      redirect_to root_url
    end
  end

  def load_participate
    @participate = Participate.find_by id: params[:id]
    unless @participate
      flash[:danger] = t "user_not_found"
      redirect_to root_url
    end
  end
end

app/views/participates/_participate.html.erb
<div class="card custom-card margin-top-20" id= "user<%= participate.user.id %>">
  <%= link_to (t "remove"), project_participate_path(I18n.locale, @project, participate),
    remote: true, method: :delete, class: "btn btn-primary" %>

  <div class="image">
    <%= image_tag participate.user.avatar.url, class: "user-index-avatar",
      data: {toggle: "modal", target: "#user_modal#{participate.user.id}"} %>
  </div>

  <div class="content">
    <div class="header">
      <%= link_to participate.user.name, user_path(I18n.locale, participate.user) %>
    </div>
    <div class="meta">
      <%= participate.user.position %>
    </div>
    <% if participate.user.biography.presence %>
      <div class="description">
        <%= participate.user.biography.truncate(Settings.truncate.biography) %>
      </div>
    <% end %>
  </div>
  <div class="extra content">
    <span class="right floated">
      <%= t "joined_in" %> <%= participate.user.created_at.year %>
    </span>
    <span>
      <i class="user icon"></i>
      <%= participate.user.projects.size %> <%= t ".projects" %>
    </span>
  </div>
</div>

<div class="modal member-modal-width fade" id="user_modal<%= participate.user.id %>" tabindex="-1" role="dialog",
  aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title" id="myModalLabel"><%= t "users.about_you" %></h4>
      </div>
      <div class="modal-body">
        <center>
          <%= image_tag participate.user.avatar.url, class: "image-modal img-circle" %>
          <h1 class="media-heading"><%= participate.user.name %></h1>
          <h2 class="media-heading"><%= participate.user.position %></h2>
          <span class="glyphicon glyphicon-star" style="color:#f4b942"></span>
          <span class="glyphicon glyphicon-star" style="color:#f4b942"></span>
          <span class="glyphicon glyphicon-star" style="color:#f4b942"></span>
          <span class="glyphicon glyphicon-star" style="color:#f4b942"></span>
          <span class="glyphicon glyphicon-star" style="color:#f4b942"></span>
        </center>
        <div class="row clearfix">
          <div class="table-responsive">
            <table class="table user-table text-left">
              <tr >
                <td class="first"><h4>
                  <span class="glyphicon glyphicon-thumbs-up" style="color:#f4b942">
                  </span><%= t "users.like" %></h4>
                </td>
                <td class="first"><h4>
                  <span class="glyphicon glyphicon-ok-sign" style="color:#f4b942">
                  </span><%= t "users.rate" %></h4>
                </td>
              </tr>
              <tr>
                <td class="first"><h4>
                  <span class="glyphicon glyphicon-list-alt" style="color:#f4b942">
                  </span><%= t "users.skill" %></h4>
                </td>
                <td class="second"><h4>
                  <span class="glyphicon glyphicon-certificate" style="color:#f4b942">
                  </span><%= t "users.cetificate" %></h4>
                </td>
              </tr>
            </table>
            <hr>
          </div>
        </div>
        <center>
          <h5 class="text-left">
            <strong>
              <span class="glyphicon glyphicon-user" >
                <%= t "users.biography" %>
                <h5><%= participate.user.biography %></h5><br>
              </span>
            </strong>
          </h5>
        </center>
      </div>
    </div>
  </div>
</div>

app/views/participates/create.js.erb
$('#project-members-<%= @project.id %>').append("<%= j render @participate %>");
$('#user-<%= @participate.user.id %>').remove();
$('#user_modal<%= @participate.user.id %>').fadeOut('fast');
$('.modal-backdrop').remove();

app/views/participates/destroy.js.erb
$('#project-members-<%= @project.id %>').html("<%= j render @project.participates %>");
$('#member-<%= @participate.user_id %>').remove();
$('#users-<%= @project.id%>').append("<%= j render @participate.user %>");

app/views/participates/index.html.erb
<div class="container form-project-new ">
  <div class="col-md-12" >
  <h2><%= t "add_member" %></h2>

  </div>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home"><%= t "member" %></a></li>
    <li><a data-toggle="tab" href="#menu2"><%= t "member_of_project" %></a></li>
    <%= link_to "Hoàn Thành", project_path(I18n.locale, @project), class: "btn btn-success" %>
  </ul>
  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <%= render "shared/list_user"%>
    </div>
    <div id="menu2" class="tab-pane fade">
      <div id="project-members-<%= @project.id %>" class="ui link cards margin-top-15">
        <%= render @participates %>
      </div>
    </div>
  </div>
</div>